# Generated by Django 2.1.5 on 2019-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190318_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('a', '文章'), ('p', '页面')], default='a', max_length=1, verbose_name='文章类型'),
        ),
    ]
