# Generated by Django 2.1.5 on 2019-05-12 23:11

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_guestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, help_text='越大越前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='content',
            field=models.TextField(max_length=250, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.IntegerField(default=0, help_text='越大越前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.TextField(help_text='用于title标签', max_length=200, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(help_text='media/', upload_to=blog.models.photo_path, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(help_text='用于当作照片名称', max_length=50, verbose_name='图片标题'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='github_repository',
            field=models.CharField(default='', help_text='https://github.com/enjoy-binbin/binblog-Django', max_length=50, verbose_name='github仓库'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='github_user',
            field=models.CharField(default='', help_text='https://github.com/enjoy-binbin', max_length=50, verbose_name='github账号'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='order',
            field=models.IntegerField(default=1, help_text='越大越前', verbose_name='排序'),
        ),
    ]
