# Generated by Django 2.1.5 on 2019-05-12 23:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190512_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['author', '-id'], 'verbose_name': '留言板', 'verbose_name_plural': '留言板'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, help_text='media/photo/', upload_to=blog.models.photo_path, verbose_name='图片'),
            preserve_default=False,
        ),
    ]
