# Generated by Django 2.1.5 on 2019-05-28 10:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190512_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-order', '-add_time'], 'verbose_name': '2-文章', 'verbose_name_plural': '2-文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '1-文章分类', 'verbose_name_plural': '1-文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '3-文章评论', 'verbose_name_plural': '3-文章评论'},
        ),
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['author', '-id'], 'verbose_name': '7-留言板', 'verbose_name_plural': '7-留言板'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order'], 'verbose_name': '8-友情链接', 'verbose_name_plural': '8-友情链接'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '6-相册图片', 'verbose_name_plural': '6-相册图片'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': '0-站点配置', 'verbose_name_plural': '0-站点配置'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['-order'], 'verbose_name': '5-侧边栏', 'verbose_name_plural': '5-侧边栏'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': '4-文章标签', 'verbose_name_plural': '4-文章标签'},
        ),
        migrations.AddField(
            model_name='setting',
            name='enable_photo',
            field=models.BooleanField(default=True, verbose_name='是否启用相册'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.TextField(blank=True, help_text='用于图片标签的title属性', max_length=200, null=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='默认保存在/media/photo/', upload_to=blog.models.photo_path, verbose_name='图片'),
        ),
    ]
