# Generated by Django 2.1.5 on 2019-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190528_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='user_verify_email',
            field=models.BooleanField(default=False, verbose_name='用户注册是否验证邮箱'),
        ),
    ]
