# Generated by Django 2.1.5 on 2019-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_setting_user_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enable_multi_user',
            field=models.BooleanField(default=False, help_text='启用多用户博客系统, 用户在注册时候会获得, 相应的后台权限', verbose_name='是否启用多用户博客系统'),
        ),
    ]
