# Generated by Django 2.1.11 on 2020-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191007_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_me',
            field=models.TextField(blank=True, default='Hello World', verbose_name='关于我'),
        ),
    ]
