# Generated by Django 2.1.11 on 2020-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_setting_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='github_avatar',
            field=models.CharField(default='https://avatars2.githubusercontent.com/u/22811481', help_text='https://avatars2.githubusercontent.com/u/22811481', max_length=50, verbose_name='github头像'),
        ),
    ]
