# Generated by Django 2.1.11 on 2020-07-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_setting_github_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('excellent', '优秀'), ('hide', '隐藏')], default='normal', max_length=10, verbose_name='文章状态'),
        ),
        migrations.AddField(
            model_name='setting',
            name='motto',
            field=models.TextField(blank=True, default='Choose what you love. Love what you choose.', help_text='GithubPage中的motto', verbose_name='座右铭'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, default='Hello World', max_length=50, verbose_name='H1标题'),
        ),
    ]
