# Generated by Django 2.1.5 on 2019-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconfig',
            name='callback_url',
            field=models.CharField(default='', help_text='http://127.0.0.1:8000/oauth/authorize?type=github', max_length=200, verbose_name='回调地址'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
    ]
