# Generated by Django 2.1.5 on 2019-05-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20190512_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthconfig',
            options={'ordering': ['-add_time'], 'verbose_name': '0-OAuth配置', 'verbose_name_plural': '0-OAuth配置'},
        ),
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'ordering': ['-add_time'], 'verbose_name': '1-Oauth用户', 'verbose_name_plural': '1-Oauth用户'},
        ),
    ]
