# Generated by Django 2.1.5 on 2019-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190530_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifycode',
            options={'verbose_name': '1-邮箱验证码', 'verbose_name_plural': '1-邮箱验证码'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '0-用户', 'verbose_name_plural': '0-用户'},
        ),
        migrations.AddField(
            model_name='emailverifycode',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='celery.task_id', max_length=36, verbose_name='任务的uuid'),
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否使用'),
        ),
    ]
